import { AtelierLocation, Language } from './types';

export const LOCATIONS: AtelierLocation[] = [
  {
    id: 'loc-1',
    type: 'atelier',
    name: 'Shanghai Flagship Atelier - The Bund',
    address: 'No. 18, The Bund, Huangpu District, Shanghai',
    hoursOrDate: 'Daily, 10:00 AM – 8:00 PM',
    phone: '+86 21 1234 5678',
    lat: 480, // X-coordinate on SVG
    lng: 320, // Y-coordinate on SVG
    description: 'Our premier historic flagship salon on the iconic Bund waterfront, featuring panoramic views of Pudong. Home to our master tailors and high-jewelry consultants.',
    imageUrl: 'https://images.unsplash.com/photo-1474181487882-5abf3f016c2d?q=80&w=600&auto=format&fit=crop',
    googleMapsUrl: 'https://maps.google.com/?q=The+Bund+Shanghai+No+18',
    appleMapsUrl: 'https://maps.apple.com/?q=The+Bund+Shanghai+No+18'
  },
  {
    id: 'loc-2',
    type: 'atelier',
    name: 'Bespoke Jewelry Studio',
    address: '322 Anfu Road, Xuhui District, Shanghai',
    hoursOrDate: 'By Appointment Only',
    phone: '+86 21 8765 4321',
    lat: 310,
    lng: 490,
    description: 'An intimate, tree-lined sanctuary in the French Concession dedicated to high jewelry design, gemstone consultation, and custom metal casting.',
    imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=600&auto=format&fit=crop',
    googleMapsUrl: 'https://maps.google.com/?q=Anfu+Road+Shanghai+322',
    appleMapsUrl: 'https://maps.apple.com/?q=Anfu+Road+Shanghai+322'
  },
  {
    id: 'loc-3',
    type: 'event',
    name: 'Pop-up: Silk & Gold Artisans',
    address: 'Jing\'an Temple Plaza, Jing\'an District, Shanghai',
    hoursOrDate: 'Oct 26 - Nov 5, 2024',
    lat: 250,
    lng: 380,
    description: 'An exclusive live craft exhibition showcasing master embroiderers and traditional filigree gold wire artists at work. Rare antique pieces on display.',
    imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=600&auto=format&fit=crop',
    googleMapsUrl: 'https://maps.google.com/?q=Jing\'an+Temple+Shanghai',
    appleMapsUrl: 'https://maps.apple.com/?q=Jing\'an+Temple+Shanghai'
  },
  {
    id: 'loc-4',
    type: 'event',
    name: 'Private View: The Art of Tailoring',
    address: 'French Concession Villa, Shanghai',
    hoursOrDate: 'Nov 10, 2024, 6:00 PM',
    lat: 380,
    lng: 560,
    description: 'An invitation-only runway and cocktail reception presenting our Autumn/Winter Bespoke Haute Couture collection in a restored 1930s garden villa.',
    imageUrl: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?q=80&w=600&auto=format&fit=crop',
    googleMapsUrl: 'https://maps.google.com/?q=French+Concession+Shanghai',
    appleMapsUrl: 'https://maps.apple.com/?q=French+Concession+Shanghai'
  }
];

export const CUSTOM_OPTIONS = {
  suit: {
    fabrics: [
      { id: 'f-1', name: 'Scabal Royal Ultrafine Wool', priceModifier: 0, colorHex: '#1d2330' },
      { id: 'f-2', name: 'Loro Piana Cashmere Blend', priceModifier: 3500, colorHex: '#2d2522' },
      { id: 'f-3', name: 'Dormeuil Diamond Silk Dust', priceModifier: 6200, colorHex: '#111419' },
      { id: 'f-4', name: 'Haipai Heritage Silk Jacquard', priceModifier: 4800, colorHex: '#42161b' }
    ],
    linings: [
      { id: 'l-1', name: 'Imperial Red Silk Charmeuse', priceModifier: 0, colorHex: '#800c14' },
      { id: 'l-2', name: 'Shanghai Deco Gold Brocade', priceModifier: 1200, colorHex: '#d4af37' },
      { id: 'l-3', name: 'Classic Midnight Satin', priceModifier: 300, colorHex: '#0c111c' },
      { id: 'l-4', name: 'Emerald Crane Jacquard', priceModifier: 1500, colorHex: '#0f382a' }
    ],
    buttons: [
      { id: 'b-1', name: 'Genuine Dark Buffalo Horn', priceModifier: 0, colorHex: '#1a1a1a' },
      { id: 'b-2', name: 'Mother of Pearl Iridescent', priceModifier: 600, colorHex: '#eae7e1' },
      { id: 'b-3', name: 'Hand-Engraved Brass Emblem', priceModifier: 1100, colorHex: '#c5a059' }
    ],
    basePrice: 18800
  },
  qipao: {
    fabrics: [
      { id: 'q-1', name: 'Suzhou Silk Mulberry Satin', priceModifier: 0, colorHex: '#e1dcd3' },
      { id: 'q-2', name: 'Imperial Phoenix Red Damask', priceModifier: 1800, colorHex: '#9c1a21' },
      { id: 'q-3', name: 'Hand-Painted Blossom Chiffon', priceModifier: 3200, colorHex: '#fcd3de' },
      { id: 'q-4', name: 'Midnight Crane Silk Velvet', priceModifier: 2400, colorHex: '#080c14' }
    ],
    linings: [
      { id: 'ql-1', name: 'Ultra-Soft Rose Silk Lining', priceModifier: 0, colorHex: '#f5e3e6' },
      { id: 'ql-2', name: 'Golden Luck Bamboo Lining', priceModifier: 600, colorHex: '#d1b26a' }
    ],
    buttons: [
      { id: 'qb-1', name: 'Traditional Hand-Knot Frog Fastener', priceModifier: 0, colorHex: '#bfa36c' },
      { id: 'qb-2', name: 'Precious Green Jade Frog Closure', priceModifier: 2800, colorHex: '#306e50' },
      { id: 'qb-3', name: 'Pearl Embedded Silk Pignois', priceModifier: 1500, colorHex: '#ece3ce' }
    ],
    basePrice: 12800
  },
  ring: {
    metals: [
      { id: 'm-1', name: '18K White Gold', priceModifier: 0, colorHex: '#e5e5e5' },
      { id: 'm-2', name: '950 Platinum Majestic', priceModifier: 3800, colorHex: '#f2f2f2' },
      { id: 'm-3', name: '18K Imperial Yellow Gold', priceModifier: 800, colorHex: '#d4af37' }
    ],
    gemstones: [
      { id: 'g-1', name: '1.5 Carat Brilliant Round Diamond (D/VS1)', priceModifier: 0, colorHex: '#e0f2fe' },
      { id: 'g-2', name: '2.0 Carat Ceylon Blue Sapphire Oval', priceModifier: 15000, colorHex: '#1e3a8a' },
      { id: 'g-3', name: '1.8 Carat Colombian Emerald Cut', priceModifier: 18500, colorHex: '#065f46' },
      { id: 'g-4', name: 'Imperial Green Jadeite Cabochon', priceModifier: 25000, colorHex: '#15803d' }
    ],
    basePrice: 45000
  },
  necklace: {
    metals: [
      { id: 'nm-1', name: '18K White Gold Chain & Mounts', priceModifier: 0, colorHex: '#e5e5e5' },
      { id: 'nm-2', name: '950 Platinum Seamless Craft', priceModifier: 6800, colorHex: '#f2f2f2' }
    ],
    gemstones: [
      { id: 'ng-1', name: 'Cascading Round Diamonds Selection', priceModifier: 0, colorHex: '#e0f2fe' },
      { id: 'ng-2', name: 'Diamond with Deep Royal Sapphire Drops', priceModifier: 32000, colorHex: '#1d4ed8' },
      { id: 'ng-3', name: 'Artisan Emerald and Diamond Garland', priceModifier: 46000, colorHex: '#047857' }
    ],
    basePrice: 88000
  }
};

export const TRANSLATIONS: Record<Language, any> = {
  fr: {
    navHome: 'Accueil',
    navServices: 'Services',
    navMap: 'Adresses & Événements',
    navProfile: 'Mon Profil',
    bookConsultation: 'Prendre Rendez-vous',
    brandSubtitle: 'ATELIER DE HAUTE COUTURE',
    heroTitle: 'L\'Art du Luxe Personnel à Shanghai',
    heroSubtitle: 'Où l\'héritage Haipai rencontre l\'artisanat d\'exception dans la haute couture et la joaillerie fine.',
    beginJourney: 'Commencez Votre Voyage',
    heritageTitle: 'HÉRITAGE HAIPAI, ARTISANAT MODERNE',
    heritagePara1: 'La fusion de l\'Orient et de l\'Occident au cœur de notre processus méticuleux de haute couture, alliant la qualité suprême et le respect des traditions séculaires.',
    heritagePara2: 'Nos maîtres artisans hautement qualifiés consacrent des centaines d\'heures à broder, couper et façonner chaque création à la perfection absolue pour les connaisseurs internationaux.',
    galleryTitle: 'GALERIE DES CRÉATIONS',
    viewFullCollection: 'Voir la collection complète',
    experienceTitle: 'L\'EXPÉRIENCE BESPOKE',
    exp1Title: 'Consultation',
    exp1Desc: 'Rencontre privée et étude personnalisée de votre vision créative.',
    exp2Title: 'Design',
    exp2Desc: 'Dessins de style uniques et prise de mesures ultra-précise.',
    exp3Title: 'Création',
    exp3Desc: 'Coupe artisanale et assemblage méticuleux par nos maîtres tailleurs.',
    exp4Title: 'Livraison',
    exp4Desc: 'Dernier essayage et livraison soignée à domicile ou en atelier.',
    scheduleTitle: 'RÉSERVER VOTRE RENDEZ-VOUS PRIVÉ',
    reqConsultationBtn: 'Demander une consultation privée',
    serviceCategoriesTitle: 'Catégories de Services',
    tailoredApparel: 'Haute Couture',
    tailoredApparelDesc: 'Du Qipao traditionnel aux costumes modernes d\'exception, nos tailleurs façonnent des vêtements d\'une coupe absolue dans des étoffes d\'exception.',
    fineJewelry: 'Haute Joaillerie',
    fineJewelryDesc: 'Créations uniques serties de pierres d\'exception. Diamants, saphirs et jade d\'une pureté absolue, façonnés à la main dans notre studio.',
    craftspotlightTitle: 'Pleins Feux sur l\'Artisanat',
    craftspotlightSubtitle: 'Détails & Textures: Qualité Sans Compromis',
    craftspotlightDesc: 'Nous sourçons uniquement les matières les plus rares, garantissant que chaque point de couture et chaque sertissage est un chef-d’œuvre de l\'art traditionnel de Shanghai.',
    processFlowTitle: 'Le Processus de Création',
    stepConsult: '1. Consultation & Design',
    stepConsultDesc: 'Rencontre privée pour dessiner votre projet selon vos goûts.',
    stepMaterial: '2. Sélection des Matières',
    stepMaterialDesc: 'Choisissez parmi nos soies précieuses, cachemires et gemmes rares.',
    stepFitting: '3. Coupe & Confection',
    stepFittingDesc: 'Mesures exactes, essayages intermédiaires et couture artisanale.',
    stepDelivery: '4. Livraison Finale',
    stepDeliveryDesc: 'La révélation finale d\'une création unique, prête à porter.',
    requestAppointmentTitle: 'Demander un rendez-vous privé',
    fullNameLabel: 'Nom complet',
    emailLabel: 'Adresse email',
    phoneLabel: 'Numéro de téléphone',
    serviceInterestLabel: 'Intérêt du service',
    prefDateTimeLabel: 'Date & heure souhaitées',
    specialNotesLabel: 'Notes spéciales / demandes',
    bookNowBtn: 'RÉSERVER MAINTENANT',
    bookConsultationSuccess: 'Votre demande de consultation a été enregistrée avec succès. Nos concierges vous contacteront sous 24 heures pour confirmer le créneau.',
    myProfile: 'Mon Profil & Réservations',
    noBookings: 'Vous n\'avez pas encore de rendez-vous.',
    statusPending: 'En attente',
    statusConfirmed: 'Confirmé',
    statusCancelled: 'Annulé',
    createdAtLabel: 'Créé le',
    customizerTitle: 'Atelier de Personnalisation Interactive',
    selectCategory: 'Choisir la catégorie',
    suitCat: 'Costume Bespoke',
    qipaoCat: 'Qipao Haute Couture',
    ringCat: 'Bague de Haute Joaillerie',
    necklaceCat: 'Collier de Diamants',
    fabricOption: 'Étoffe / Matière',
    liningOption: 'Doublure',
    buttonOption: 'Boutons / Fermoirs',
    metalOption: 'Métal précieux',
    gemstoneOption: 'Pierre précieuse',
    monogramPlaceholder: 'Initiales (Ex: MT)',
    monogramLabel: 'Monogramme personnalisé (Gratuit)',
    estPrice: 'Prix de référence estimé',
    customizeBtn: 'Personnaliser dans l\'Atelier',
    addToAppointment: 'Joindre cette création à mon rendez-vous',
    closeBtn: 'Fermer',
    locatorTitle: 'Adresses & Événements',
    allLocations: 'Tous les lieux',
    ateliersOnly: 'Ateliers Flagship',
    eventsOnly: 'Événements Exclusifs',
    navigateBtn: 'Naviguer',
    rsvpBtn: 'S\'inscrire / RSVP',
    rsvpSuccess: 'Votre inscription pour l\'événement a été enregistrée avec succès! Une invitation officielle vous sera envoyée.',
    viewDetails: 'Détails',
    interactiveMapDesc: 'Explorez nos ateliers exclusifs et nos salons privés au cœur de Shanghai.',
    tailoringJourneyTitle: 'Le Parcours de Confection',
    priceStarting: 'À partir de',
    personalizedAcc: 'Accessoires Personnalisés',
    tailoredEvening: 'Robes du Soir sur Mesure',
    fineGemstone: 'Joaillerie de Prestige'
  },
  en: {
    navHome: 'Home',
    navServices: 'Services',
    navMap: 'Map & Events',
    navProfile: 'My Profile',
    bookConsultation: 'Book Consultation',
    brandSubtitle: 'BESPOKE ATELIER',
    heroTitle: 'The Art of Personal Luxury in Shanghai',
    heroSubtitle: 'Where Haipai heritage meets modern craftsmanship in bespoke fashion and fine jewelry.',
    beginJourney: 'Begin Your Journey',
    heritageTitle: 'HAIPAI HERITAGE, MODERN CRAFT',
    heritagePara1: 'The fusion of East and West in our meticulous bespoke process, marrying ultimate quality, cast and embroidery process options for fine fashion and jewelry.',
    heritagePara2: 'We have heavily nominated master artisans of beautiful century-old traditions to maintain a value of quality tailored and rooted as we create elegant items for the best global connoisseurs.',
    galleryTitle: 'CUSTOMIZATION GALLERY',
    viewFullCollection: 'View Full Collection',
    experienceTitle: 'THE BESPOKE EXPERIENCE',
    exp1Title: 'Consultation',
    exp1Desc: 'Private meeting and custom curation of your creative vision.',
    exp2Title: 'Design',
    exp2Desc: 'Design a custom style with high-quality and fitting design.',
    exp3Title: 'Creation',
    exp3Desc: 'Creation on coded tailoring and your precise unique process.',
    exp4Title: 'Delivery',
    exp4Desc: 'Final fitting and premium home or atelier delivery.',
    scheduleTitle: 'SCHEDULE YOUR PRIVATE APPOINTMENT',
    reqConsultationBtn: 'Request Consultation Now',
    serviceCategoriesTitle: 'Service Categories',
    tailoredApparel: 'Tailored Apparel',
    tailoredApparelDesc: 'From traditional Qipao to modern bespoke suits, our master tailors create garments that fit you perfectly, using the finest fabrics.',
    fineJewelry: 'Fine Jewelry',
    fineJewelryDesc: 'Design unique pieces with our artisans, utilizing precious gems and metals for timeless elegance.',
    craftspotlightTitle: 'Craftsmanship Spotlight',
    craftspotlightSubtitle: 'Details & Textures: Uncompromising Quality',
    craftspotlightDesc: 'We source only the rarest materials, ensuring every stitch and setting is a masterpiece of Shanghai artistry.',
    processFlowTitle: 'Process Flow',
    stepConsult: '1. Consultation & Design',
    stepConsultDesc: 'Private meeting with our designers to choose your vision and requirements.',
    stepMaterial: '2. Material Selection',
    stepMaterialDesc: 'Choose from exclusive fabrics, leathers, and precious stones.',
    stepFitting: '3. Fitting & Creation',
    stepFittingDesc: 'Intermediate fitting and meticulous crafting by our artisans.',
    stepDelivery: '4. Final Delivery',
    stepDeliveryDesc: 'Receive your finished, one-of-a-kind creation.',
    requestAppointmentTitle: 'Request a Private Appointment',
    fullNameLabel: 'Full Name',
    emailLabel: 'Email Address',
    phoneLabel: 'Phone Number',
    serviceInterestLabel: 'Services Interest',
    prefDateTimeLabel: 'Preferred Date & Time',
    specialNotesLabel: 'Special Notes / Requests',
    bookNowBtn: 'REQUEST PRIVATE APPOINTMENT',
    bookConsultationSuccess: 'Your appointment request has been recorded successfully. Our concierge will contact you within 24 hours to finalize.',
    myProfile: 'My Profile & Bookings',
    noBookings: 'You do not have any appointments scheduled yet.',
    statusPending: 'Pending',
    statusConfirmed: 'Confirmed',
    statusCancelled: 'Cancelled',
    createdAtLabel: 'Created on',
    customizerTitle: 'Interactive Customization Atelier',
    selectCategory: 'Select Category',
    suitCat: 'Bespoke Suit',
    qipaoCat: 'Tailored Qipao',
    ringCat: 'High Jewelry Ring',
    necklaceCat: 'Diamond Necklace',
    fabricOption: 'Fabric / Material',
    liningOption: 'Lining',
    buttonOption: 'Buttons / Clasps',
    metalOption: 'Precious Metal',
    gemstoneOption: 'Gemstone',
    monogramPlaceholder: 'Initials (e.g. MT)',
    monogramLabel: 'Personalized Monogram (Complimentary)',
    estPrice: 'Estimated Price Reference',
    customizeBtn: 'Customize in Atelier',
    addToAppointment: 'Attach this creation to my appointment',
    closeBtn: 'Close',
    locatorTitle: 'Ateliers & Events',
    allLocations: 'All Locations',
    ateliersOnly: 'Flagship Ateliers',
    eventsOnly: 'Exclusive Events',
    navigateBtn: 'Navigate',
    rsvpBtn: 'RSVP / Register',
    rsvpSuccess: 'Your RSVP has been registered successfully! An invitation card is on its way.',
    viewDetails: 'Details',
    interactiveMapDesc: 'Explore our boutique flagship locations and private salons in Shanghai.',
    tailoringJourneyTitle: 'Confection Journey',
    priceStarting: 'Starting from',
    personalizedAcc: 'Personalized Accessories',
    tailoredEvening: 'Tailored Evening Wear',
    fineGemstone: 'Fine Gemstone Jewelry'
  },
  cn: {
    navHome: '首页',
    navServices: '定制服务',
    navMap: '店铺与活动',
    navProfile: '个人中心',
    bookConsultation: '预约咨询',
    brandSubtitle: '上海高定工坊',
    heroTitle: '上海私人奢华艺术',
    heroSubtitle: '海派传承与现代工艺在高级定制服装和高级珠宝中完美交融。',
    beginJourney: '开启您的璀璨之旅',
    heritageTitle: '海派传承，现代匠心',
    heritagePara1: '在精益求精的定制流程中融合东西方美学，为您提供卓越面料和精美珠宝的个性化选择。',
    heritagePara2: '我们拥有百年工艺传承的资深工匠，精心雕琢每一件高定作品，只为契合全球鉴赏家的独特品味。',
    galleryTitle: '定制作品展厅',
    viewFullCollection: '查看完整系列',
    experienceTitle: '高定专享体验',
    exp1Title: '尊享咨询',
    exp1Desc: '私人会面，专属定制您的创意愿景与时尚理念。',
    exp2Title: '设计草图',
    exp2Desc: '为您手绘独一无二的设计图纸并进行精准量体。',
    exp3Title: '手工缝制',
    exp3Desc: '工坊大师精工细作，倾心缝制您的专属高定华服。',
    exp4Title: '尊贵交付',
    exp4Desc: '终极试穿调整，提供工坊交付或专人送货上门。',
    scheduleTitle: '预约您的专属私人咨询',
    reqConsultationBtn: '立即预约私人咨询',
    serviceCategoriesTitle: '服务类别',
    tailoredApparel: '高级定制华服',
    tailoredApparelDesc: '从传统手工旗袍到现代绅士西装，我们的工坊大师使用最顶级的面料为您量身打造完美贴合的服饰。',
    fineJewelry: '高级珠宝定制',
    fineJewelryDesc: '与我们的珠宝大师共同设计独特珍品，精选珍贵宝石与贵金属，绽放永恒优雅。',
    craftspotlightTitle: '匠心闪耀',
    craftspotlightSubtitle: '细节与质感：不妥协的至臻品质',
    craftspotlightDesc: '我们仅选用全球最珍稀的原料，确保每一针一线、每一颗宝石的镶嵌都成为上海海派高定艺术的杰作。',
    processFlowTitle: '高定流程',
    stepConsult: '1. 咨询与设计',
    stepConsultDesc: '私人设计师会面，确立创意愿景与各项个性化需求。',
    stepMaterial: '2. 臻选面料/宝石',
    stepMaterialDesc: '从限量供应的面料、名贵皮革和稀有宝石中挑选心仪材质。',
    stepFitting: '3. 试穿与匠心缝制',
    stepFittingDesc: '进行中间试穿调整，工坊匠人手工为您量体剪裁、细密缝制。',
    stepDelivery: '4. 尊贵交付',
    stepDeliveryDesc: '收获您独一无二的高定杰作，开启极致品味。',
    requestAppointmentTitle: '预约您的私人咨询',
    fullNameLabel: '您的姓名',
    emailLabel: '邮箱地址',
    phoneLabel: '联系电话',
    serviceInterestLabel: '意向服务类别',
    prefDateTimeLabel: '期望预约日期与时间',
    specialNotesLabel: '特别要求/定制备注',
    bookNowBtn: '提交私人预约申请',
    bookConsultationSuccess: '您的预约申请已成功提交。我们的高定客服专员将在24小时内与您联系确认。',
    myProfile: '我的预约与定制',
    noBookings: '您目前尚无预约记录。',
    statusPending: '待审核',
    statusConfirmed: '已确认',
    statusCancelled: '已取消',
    createdAtLabel: '申请提交于',
    customizerTitle: '交互式高定工坊体验',
    selectCategory: '选择高定类别',
    suitCat: '绅士西装 Bespoke',
    qipaoCat: '海派旗袍 Qipao',
    ringCat: '高级定制戒指',
    necklaceCat: '高级钻石吊坠',
    fabricOption: '定制面料 / 材质',
    liningOption: '内衬选择',
    buttonOption: '纽扣 / 盘扣',
    metalOption: '贵金属材质',
    gemstoneOption: '珍稀宝石',
    monogramPlaceholder: '请输入姓名首字母 (例如: MT)',
    monogramLabel: '专属刺绣/镌刻印记 (免费赠予)',
    estPrice: '高定估算价格参考',
    customizeBtn: '进入工坊在线设计',
    addToAppointment: '将此设计附带至我的咨询预约中',
    closeBtn: '关闭工坊',
    locatorTitle: '上海旗舰工坊与沙龙',
    allLocations: '全部地点',
    ateliersOnly: '品牌旗舰工坊',
    eventsOnly: '专属沙龙活动',
    navigateBtn: '路线导航',
    rsvpBtn: '受邀登记 / RSVP',
    rsvpSuccess: '您的沙龙受邀登记已成功！电子邀请函正发送至您的账户。',
    viewDetails: '详情',
    interactiveMapDesc: '探索我们位于上海核心地带的旗舰工坊与私人会客沙龙。',
    tailoringJourneyTitle: '尊享定制流程',
    priceStarting: '起步价',
    personalizedAcc: '定制配饰皮具',
    tailoredEvening: '高定晚礼服',
    fineGemstone: '海派传世珠宝'
  }
};
